firstName: Fikri
middleName: Khairul
lastName: Shaleh
hobbies:
  - Coding
  - Reading
  - Gaming
address:
  street: Jln.Kibledug Jaya
  city: Cirebon
  province: West Java
  country: Indonesia
wallet:
  -type: cash
   amount: 1000000
  -type: debit
   amount: 2000000